### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nerdprogrammergm** [machinebox/webcamFacebox#1]
Setup is perfectly done, still when I try to execute the build on my mac, and browse the url localhost:8081/camFacebox, I am getting this error, please help.
"2017/10/10 18:14:12 [ERROR] reading next part multipart: NextPart: EOF"

**Comment by dahernan** [comment]
try just to run capture.py alone, you'll probably don't have installed python requeriements, specially OpenCV could be tricky to install properly

**Comment by nerdprogrammergm** [comment]
Thanks man, It resolved the issue, cv2 was messing up.
Now the problem is capture.py is executing fine but when I make build of webcamFacebox by doing "go build" and the executing the build by using "./webcamFacebox", the app does not respond at all, nothing new appears in the console and nor on the web browser.

**Comment by dahernan** [comment]
If you look the source code
https://github.com/machinebox/webcamFacebox/blob/master/main.go#L22-L28
it does not print anything.

Just visit http://localhost:8081/cam

**Comment by nerdprogrammergm** [comment]
Ah, sorry, yet did not went through the code as just trying this awesome box, well man you rock once again, you are right, it works on http://localhost:98081/webcamFacebox.
Thanks alot for quick reply :) and keep rocking in development really like such kind of application and also developing them :)
